import type { Completion, CompletionContext, CompletionResult } from '@codemirror/autocomplete';

// ── Completion item helpers ───────────────────────────────────────────────────

function fn(label: string, detail: string, info?: string): Completion {
    return { label, type: 'function', detail, info };
}
function variable(label: string, info?: string): Completion {
    return { label, type: 'variable', info };
}
function ns(label: string, info?: string): Completion {
    return { label, type: 'namespace', info };
}
function kw(label: string): Completion {
    return { label, type: 'keyword' };
}

// ── io ────────────────────────────────────────────────────────────────────────

const IO_COMPLETIONS: Completion[] = [
    fn('open',   '(filename, mode?) → file',  'Open a file. mode: "r" (default), "w", "a", "r+", "w+", "a+"'),
    fn('close',  '([file])',                   'Close a file handle'),
    fn('lines',  '(filename, fmt?)',           'Iterate lines of a file'),
    fn('input',  '([file]) → file',            'Get or set the default input file (filename or handle). io.read uses it.'),
    fn('output', '([file]) → file',            'Get or set the default output file (filename or handle). io.write uses it.'),
    fn('read',   '(...) → ...',                'Read from the default input file (set via io.input). stdin is not supported.'),
    fn('write',  '(...)',                      'Write to the default output file (set via io.output). stdout is not supported; use echo().'),
    fn('type',   '(obj) → string|nil',         'Return "file", "closed file", or nil'),
];

// ── lfs ───────────────────────────────────────────────────────────────────────

const LFS_COMPLETIONS: Completion[] = [
    fn('mkdir',      '(path) → true|nil,err',          'Create a directory (recursive)'),
    fn('rmdir',      '(path) → true|nil,err',          'Remove a directory'),
    fn('dir',        '(path) → iterator',              'Iterate directory entries'),
    fn('attributes', '(path, [attr]) → table|value',  'Get file/directory attributes (mode, size, modification, access)'),
    fn('currentdir', '() → string',                   'Get current working directory'),
    fn('chdir',      '(path) → true|nil,err',          'Change current working directory'),
    fn('touch',      '(path)',                         'Create file if it does not exist'),
];

// ── string extensions ─────────────────────────────────────────────────────────

const STRING_EXT: Completion[] = [
    fn('format',  '(fmt, ...) → string',         'Format a string (printf-style)'),
    fn('len',     '(s) → number',                'Length of string'),
    fn('sub',     '(s, i, j?) → string',         'Substring'),
    fn('find',    '(s, pattern, init?, plain?)', 'Find pattern in string'),
    fn('match',   '(s, pattern, init?)',         'Match pattern, return captures'),
    fn('gmatch',  '(s, pattern)',                'Iterator over all matches'),
    fn('gsub',    '(s, pattern, repl, n?)',      'Global substitution'),
    fn('byte',    '(s, i?, j?)',                 'Return numeric codes of characters'),
    fn('char',    '(...) → string',              'Build string from char codes'),
    fn('rep',     '(s, n, sep?) → string',       'Repeat string'),
    fn('lower',   '(s) → string',               'Convert to lowercase'),
    fn('upper',   '(s) → string',               'Convert to uppercase'),
    fn('reverse', '(s) → string',               'Reverse a string'),
    // Mudlet extensions
    fn('split',    '(s, sep) → table',   'Split string by separator'),
    fn('starts',   '(s, prefix) → bool', 'Check if string starts with prefix'),
    fn('ends',     '(s, suffix) → bool', 'Check if string ends with suffix'),
    fn('trim',     '(s) → string',       'Strip leading/trailing whitespace'),
    fn('contains', '(s, sub) → bool',   'Check if string contains substring'),
];

// ── table extensions ──────────────────────────────────────────────────────────

const TABLE_EXT: Completion[] = [
    fn('insert',   '(t, [pos,] v)',      'Insert element into table'),
    fn('remove',   '(t, [pos])',         'Remove element from table'),
    fn('concat',   '(t, sep?, i?, j?)', 'Concatenate table elements'),
    fn('sort',     '(t, comp?)',         'Sort table in-place'),
    fn('unpack',   '(t, i?, j?)',        'Unpack table into arguments'),
    fn('move',     '(a1, f, e, t, a2?)','Move table elements'),
    // Mudlet extensions
    fn('contains', '(t, val) → bool',   'Check if table contains a value'),
    fn('size',     '(t) → number',      'Count all entries in a table (incl. non-sequential)'),
];

// ── math ──────────────────────────────────────────────────────────────────────

const MATH_EXT: Completion[] = [
    fn('abs',        '(x)',       'Absolute value'),
    fn('ceil',       '(x)',       'Round up'),
    fn('floor',      '(x)',       'Round down'),
    fn('sqrt',       '(x)',       'Square root'),
    fn('max',        '(...)',     'Maximum value'),
    fn('min',        '(...)',     'Minimum value'),
    fn('random',     '(m?, n?)', 'Random number'),
    fn('randomseed', '(x)',      'Seed random number generator'),
    fn('sin',        '(x)',      'Sine'),
    fn('cos',        '(x)',      'Cosine'),
    fn('tan',        '(x)',      'Tangent'),
    fn('atan',       '(y, x?)', 'Arctangent'),
    fn('exp',        '(x)',      'e^x'),
    fn('log',        '(x, b?)', 'Logarithm'),
    fn('fmod',       '(x, y)',  'Floating-point modulo'),
    fn('huge',       '',        'Positive infinity (math.huge)'),
    fn('pi',         '',        'Pi constant'),
    fn('maxinteger', '',        'Maximum integer value'),
    fn('mininteger', '',        'Minimum integer value'),
    fn('type',       '(x)',     'Return "integer", "float", or false'),
    fn('tointeger',  '(x)',     'Convert to integer, or nil'),
];

// ── Lua keywords ──────────────────────────────────────────────────────────────

const LUA_KEYWORDS: Completion[] = [
    'and','break','do','else','elseif','end','false','for','function',
    'goto','if','in','local','nil','not','or','repeat','return',
    'then','true','until','while',
].map(kw);

// ── Standard global functions ─────────────────────────────────────────────────

const LUA_GLOBALS: Completion[] = [
    fn('assert',       '(v, msg?)',        'Raise error if v is falsy'),
    fn('error',        '(msg, level?)',    'Raise an error'),
    fn('ipairs',       '(t)',              'Iterator for sequential table'),
    fn('pairs',        '(t)',              'Iterator for all table keys'),
    fn('pcall',        '(fn, ...)',        'Protected call; returns ok, result'),
    fn('xpcall',       '(fn, handler, ...)','Protected call with error handler'),
    fn('select',       '(index, ...)',     'Select from varargs'),
    fn('setmetatable', '(t, mt)',          'Set metatable on table'),
    fn('getmetatable', '(t)',              'Get metatable'),
    fn('rawget',       '(t, k)',           'Get without __index'),
    fn('rawset',       '(t, k, v)',        'Set without __newindex'),
    fn('rawequal',     '(a, b)',           'Equality without metamethod'),
    fn('rawlen',       '(t)',              'Length without __len'),
    fn('tostring',     '(x)',              'Convert to string'),
    fn('tonumber',     '(x, base?)',       'Convert to number'),
    fn('type',         '(x)',              'Return type name'),
    fn('unpack',       '(t, i?, j?)',      'Unpack table (Lua 5.1 compat alias)'),
    fn('next',         '(t, k?)',          'Next key/value pair in table'),
    fn('require',      '(modname)',        'Load a module'),
    fn('print',        '(...)',            'Print to stdout (use echo() for MUD output)'),
    variable('_G',     'Global environment table'),
    variable('_VERSION', 'Lua version string'),
    ns('string', 'String library'),
    ns('table',  'Table library'),
    ns('math',   'Math library'),
    ns('io',     'I/O library'),
    ns('os',     'OS library'),
    ns('utf8',   'UTF-8 library'),
];

// ── Mudlet-compatible globals ─────────────────────────────────────────────────

const MUDLET_GLOBALS: Completion[] = [
    // Output
    fn('send',         '(text)',           'Send a command to the MUD'),
    fn('sendAll',      '(...)',            'Send multiple commands'),
    fn('sendGMCP',     '(message)',        'Send a GMCP message (e.g. `Module.Sub args`)'),
    fn('sendMSDP',     '(variable [, value, ...])', 'Send an MSDP variable request/update (IAC SB MSDP …)'),
    fn('sendSocket',   '(data)',           'Send literal bytes over the socket (no telnet/encoding processing)'),
    fn('feedTelnet',   '(data)',           'Inject raw server bytes into the inbound pipeline as if received from the MUD'),
    fn('disconnect',   '()',               'Drop the current connection'),
    fn('denyCurrentSend', '()',            'Inside a sysDataSendRequest handler, cancels the in-flight command'),
    fn('echo',         '([window,] text)', 'Print plain text (optional window name as 1st arg)'),
    fn('cecho',        '([window,] text)', 'Print with Mudlet color tags'),
    fn('decho',        '([window,] text)', 'Print with decimal RGB colors'),
    fn('hecho',        '([window,] text)', 'Print with hex RGB colors'),
    fn('fg',           '(colorName)',      'Set foreground color'),
    fn('bg',           '(colorName)',      'Set background color'),
    fn('resetFormat',  '()',               'Reset text formatting'),
    fn('feedTriggers', '(text)',           'Feed text through triggers'),
    fn('deleteLine',   '([window])',       'Delete current trigger line'),
    fn('wrapLine',     '([window,] lineNumber)', 'Re-display a line (0-indexed), re-interpreting embedded \\n and re-wrapping'),
    fn('insertText',   '([window,] text)', 'Insert text at trigger cursor'),
    fn('cinsertText',  '([window,] text)', 'Insert Mudlet-color-tagged text at trigger cursor'),
    fn('dinsertText',  '([window,] text)', 'Insert decimal-RGB-formatted text at trigger cursor'),
    fn('hinsertText',  '([window,] text)', 'Insert hex-RGB-formatted text at trigger cursor'),
    fn('prefix',       '(text [, func, fgc, bgc, window])', 'Prepend text to the current trigger line. func = echo|cecho|decho|hecho (default echo)'),
    fn('suffix',       '(text [, func, fgc, bgc, window])', 'Append text to the current trigger line. func = echo|cecho|decho|hecho (default echo)'),
    fn('replace',       '([window,] text)', 'Replace current selection with plain text'),
    fn('creplace',      '([window,] text)', 'Replace current selection with Mudlet-color-tagged text'),
    fn('dreplace',      '([window,] text)', 'Replace current selection with decimal-RGB text'),
    fn('hreplace',      '([window,] text)', 'Replace current selection with hex-RGB text'),
    fn('replaceLine',   '([window,] text)', 'Replace the entire current trigger line with plain text'),
    fn('creplaceLine',  '([window,] text)', 'Replace the entire current trigger line with Mudlet-color-tagged text'),
    fn('dreplaceLine',  '([window,] text)', 'Replace the entire current trigger line with decimal-RGB text'),
    fn('hreplaceLine',  '([window,] text)', 'Replace the entire current trigger line with hex-RGB text'),
    fn('replaceAll',    '(what, with [, keepColor])',         'Replace every occurrence of `what` on the current line'),
    fn('replaceWildcard','(which, replacement [, keepColor])','Replace the Nth regex wildcard match on the current line'),
    fn('gagLine',       '()',               'Gag (suppress) the current trigger line from main output'),
    fn('deleteMultiline','([triggerDelta])','Delete all lines that matched the current multiline trigger'),
    fn('cfeedTriggers', '(text)',           'Feed Mudlet-color-tagged text through the trigger pipeline'),
    fn('dfeedTriggers', '(text)',           'Feed decimal-RGB-formatted text through the trigger pipeline'),
    fn('hfeedTriggers', '(text)',           'Feed hex-RGB-formatted text through the trigger pipeline'),
    fn('display',      '(...)',             'Pretty-print each argument to output'),
    fn('printError',   '(text)',           'Print an error message'),
    fn('printDebug',   '(msg [, showStackTrace])', 'Debug-print a message; optional stack trace'),
    fn('printTable',   '(t)',               'Pretty-print a table to output'),
    fn('showColors',   '([columns, filterColor, sort])', 'Show all named colors in the output buffer'),
    fn('showCaptureGroups', '()',           'Show the regex capture groups for the current trigger'),
    fn('showMultimatches',  '()',           'Show the multimatches table for the current multiline trigger'),
    fn('showAnsiColors', '()',              'Show all ANSI colors in the output buffer'),
    fn('closestColor',  '(r, g, b) | (color) → name, distance', 'Find the closest named color to an RGB triplet (or named color)'),
    fn('getColorWildcard', '(ansiNum) → r, g, b',   'Get the RGB triplet for an ANSI color number'),
    fn('getHTMLformat', '(formatTable) → string',   'Build the HTML <span> tag for a format table'),
    fn('getLabelFormat','(labelName) → table',      'Get the format table for a label'),
    fn('f',             '(str) → string',           'F-string interpolation: `{expr}` placeholders evaluated in the caller scope, e.g. f"hello {name}"'),
    // Color / format conversions
    fn('ansi2decho',   '(text [, defaultColor]) → string', 'Convert ANSI escape codes to decho format'),
    fn('ansi2string',  '(text) → string',                  'Strip ANSI escape codes, return plain text'),
    fn('cecho2ansi',   '(str) → string',                   'Convert Mudlet-color tags to ANSI escape codes'),
    fn('cecho2decho',  '(str) → string',                   'Convert Mudlet-color tags to decho format'),
    fn('cecho2hecho',  '(str) → string',                   'Convert Mudlet-color tags to hex (hecho) format'),
    fn('cecho2html',   '(str [, resetFormat]) → string',  'Convert Mudlet-color tags to HTML'),
    fn('cecho2string', '(formatted) → string',             'Strip Mudlet-color tags, return plain text'),
    fn('decho2ansi',   '(text) → string',                  'Convert decho-formatted text to ANSI escape codes'),
    fn('decho2cecho',  '(str) → string',                   'Convert decho format to Mudlet-color tags'),
    fn('decho2hecho',  '(str) → string',                   'Convert decho format to hex (hecho)'),
    fn('decho2html',   '(str [, resetFormat]) → string',  'Convert decho format to HTML'),
    fn('decho2string', '(formatted) → string',             'Strip decho codes, return plain text'),
    fn('hecho2ansi',   '(text) → string',                  'Convert hex (hecho) format to ANSI escape codes'),
    fn('hecho2cecho',  '(str) → string',                   'Convert hex (hecho) format to Mudlet-color tags'),
    fn('hecho2decho',  '(str) → string',                   'Convert hex (hecho) format to decho'),
    fn('hecho2html',   '(str [, resetFormat]) → string',  'Convert hex (hecho) format to HTML'),
    fn('hecho2string', '(formatted) → string',             'Strip hecho codes, return plain text'),
    fn('copy2decho',   '([window, stringToCopy, instance])', 'Copy text/selection into clipboard as decho-formatted'),
    fn('copy2html',    '([window, stringToCopy, instance])', 'Copy text/selection into clipboard as HTML'),
    // Windows
    fn('openUserWindow',  '(name, restoreLayout?, autoDock?, dockingArea?)', 'Open a user window'),
    fn('openMapWidget',   '([area | x, y, w, h])',                          'Open the map widget. No args: saved layout (right by default). One arg: dock area "f"/"l"/"r"/"t"/"b". Four args: floating at x,y with size w,h.'),
    fn('createMiniConsole', '([parent,] name, x, y, w, h) → bool', 'Create a positioned floating text panel; calling again repositions it'),
    fn('deleteMiniConsole', '(name) → bool', 'Destroy a mini-console created by createMiniConsole. Returns false for the main window, dock panels, or an unknown name.'),
    fn('createMapper',      '([parent,] x, y, w, h) → bool',        'Create a positioned mapper widget embedded in the main window or a userwindow (shares state with the dock widget). Singleton — calling again repositions it.'),
    fn('createBuffer',    '(name)',        'Create a named off-screen text buffer (like a hidden miniconsole) for formatting/storing rich text'),
    fn('copy',            '([window])',    'Copy the current selection (with formatting) into the clipboard for paste()/appendBuffer()'),
    fn('paste',           '([window])',    'Paste the copied rich text at the cursor (or append at the end of the last line)'),
    fn('appendBuffer',    '([window])',    'Append the copied rich text (see copy) as a new line to a window or buffer'),
    fn('clearWindow',     '([name])',      'Clear window contents'),
    fn('setUserWindowTitle', '(name, title)', 'Set user window title'),
    fn('setUserWindowStyleSheet', '(name, css)', 'Apply Qt-style CSS to a userwindow viewport. `QWidget { … }` (and bare declarations) auto-scope to that window so padding/background actually affect it; non-QWidget selectors are dropped.'),
    fn('hideWindow',      '(name)',        'Hide a userwindow or label'),
    fn('showWindow',      '(name)',        'Show a userwindow or label'),
    fn('moveWindow',      '(name, x, y)',  'Move a userwindow or label to a pixel position'),
    fn('resizeWindow',    '(name, w, h)',  'Resize a userwindow or label'),
    fn('setBackgroundColor', '([name,] r, g, b [, a])', 'Set a window background color (rgba 0..255). No name targets the main window. A name targets a userwindow, miniconsole, or label (labels also implicitly enable fillBackground).'),
    fn('getBackgroundColor', '([name]) → r, g, b, a', 'Get a window background color (rgba 0..255). No name returns the main window color; otherwise targets a userwindow, miniconsole, or label. Returns 0,0,0,255 when no color is set.'),
    fn('setHexFgColor',      '([window,] hexString)',   'Set foreground color from a hex string (e.g. "FF8800")'),
    fn('setHexBgColor',      '([window,] hexString)',   'Set background color from a hex string (e.g. "FF8800")'),
    fn('setBackgroundImage', '([windowName | labelName,] imageLocation [, mode])', 'Set a background image on a label, miniconsole / userwindow, or the main window. mode (1 border/stretched, 2 center, 3 tile, 4 raw stylesheet) only applies to consoles — labels ignore it. Mudlet string modes ("border" / "center" / "tile" / "style") are translated via mudlet.BgImageMode. Image paths are resolved against the active package VFS.'),
    fn('resetBackgroundImage', '([windowName])', 'Clear the background image set by setBackgroundImage. No name (or "main") clears the main window; otherwise targets a label, miniconsole, or userwindow.'),
    fn('createConsole',      '([userwindow,] name, fontSize, charsPerLine, numberOfLines, x, y)', 'Create a fixed-size text miniconsole'),
    fn('resetUserWindowTitle', '(windowName)',          'Reset a user window title back to its default'),
    fn('scrollUp',           '([window,] [lines])',     'Scroll the window up by N lines (default 1)'),
    fn('scrollDown',         '([window,] [lines])',     'Scroll the window down by N lines (default 1)'),
    fn('scrollTo',           '([window,] [lineNumber])', 'Scroll a console to a buffer line (negative counts from end). With no line, or a line past end, resume tail mode.'),
    fn('getScroll',          '([window]) → number',     'Buffer line index at the top of the console viewport. Returns the last line number when in tail mode.'),
    fn('disableScrollBar',   '([window])',              "Hide the vertical scrollbar gutter on a console wrapper. Wheel/keyboard scrolling keeps working — only the gutter visibility is affected."),
    fn('enableScrollBar',    '([window])',              'Show the vertical scrollbar gutter on a console wrapper.'),
    fn('disableHorizontalScrollBar', '([window])',      'Hide the horizontal scrollbar gutter. mudix wraps long lines by default, so this is rarely needed; included for Mudlet parity.'),
    fn('enableHorizontalScrollBar',  '([window])',      'Show the horizontal scrollbar gutter on a console wrapper.'),
    fn('disableScrolling',   '([window]) → bool',       "Lock a console to tail mode — wheel/touch/keys cannot scroll back. Returns false for 'main' (forbidden per Mudlet)."),
    fn('enableScrolling',    '([window]) → bool',       "Re-enable user scrolling on a console previously locked with disableScrolling. Returns false for 'main'."),
    fn('resetMapWindowTitle','()',                      'Reset the map window title to default'),
    fn('moveMapWidget',      '(x, y)',                  'Move the floating map widget to screen position (x, y)'),
    fn('resizeMapWidget',    '(width, height)',         'Resize the floating map widget'),
    fn('getMainWindowSize', '() → w, h',   'Main output area pixel size (live element box). Falls back to browser inner size if the main output is not mounted.'),
    fn('getMousePosition',  '() → x, y',   'Last-known cursor position in main-output-local pixels. Tracked passively via pointermove/mousedown — returns 0,0 before any pointer activity. Negative or out-of-range when the cursor is outside the main viewport.'),
    fn('getUserWindowSize', '(name) → w, h', 'Userwindow / miniconsole pixel size. Reports the live rendered box when mounted, else the stored hint. Returns 0,0 when the window does not exist.'),
    fn('hasFocus',          '([window]) → bool', 'True when the named console (or the main command bar when omitted) holds keyboard focus.'),
    fn('alert',             '([seconds])',   'Flash for attention. Browsers can\'t flash the taskbar, so mudix flashes the document title for `seconds` (default 10). No-op while the tab is already focused.'),
    fn('setFontSize',       '([window,] size) → bool',  'Set the output font size (1..99). No window arg targets the main output (persists in settings); a window name targets a userwindow or miniconsole.'),
    fn('setMiniConsoleFontSize', '(name, size) → bool', 'Set the font size (1..99) of a named miniconsole. Returns (nil, errMsg) when the name is not a miniconsole or the size is out of range.'),
    fn('getFontSize',       '([window]) → number|false','Get the configured output font size in pixels. No window arg returns the main size; a window name returns its override (or the main size if none).'),
    fn('calcFontSize',      '(size[, family]) | (windowName) → w, h',
       'Measure the average character cell of the named window or of an explicit size/family combo. Returns pixel width, height — use it to size a miniconsole to fit N cols × M rows. Returns (nil, errMsg) for an unknown window or invalid size.'),
    fn('setFont',           '([window,] family) → bool','Set the output font family. No window arg targets the main output (persists in settings as a system font); a window name targets a userwindow or miniconsole. Empty string clears the override.'),
    fn('getFont',           '([window]) → string|false','Get the configured output font family. No window arg returns the main font; a window name returns its override (or the main font if none).'),
    fn('getAvailableFonts', '() → table',               'Set-style table {[family]=true} of fonts usable from scripts: universal web-safe families, every font registered with the browser FontFaceSet (URL/VFS uploads), the profile output font, and locally-installed system fonts when Local Font Access permission has been granted.'),
    // Borders
    fn('setBorderTop',     '(size)',         'Carve a top border (in pixels) out of the main window for label placement.'),
    fn('setBorderBottom',  '(size)',         'Carve a bottom border (in pixels) out of the main window for label placement.'),
    fn('setBorderLeft',    '(size)',         'Carve a left border (in pixels) out of the main window for label placement.'),
    fn('setBorderRight',   '(size)',         'Carve a right border (in pixels) out of the main window for label placement.'),
    fn('setBorderSizes',   '(size | top, right, bottom, left)', 'Set all four border sizes at once. One arg = uniform; four args = CSS-style top/right/bottom/left.'),
    fn('getBorderTop',     '() → number',    'Pixel size of the main window top border.'),
    fn('getBorderBottom',  '() → number',    'Pixel size of the main window bottom border.'),
    fn('getBorderLeft',    '() → number',    'Pixel size of the main window left border.'),
    fn('getBorderRight',   '() → number',    'Pixel size of the main window right border.'),
    fn('getBorderSizes',   '() → {top, right, bottom, left}', 'Get all four main window border sizes as a table.'),
    fn('setBorderColor',   '(r, g, b [, a])','Fill the carved border area with an rgba color (0..255). Alpha defaults to 255.'),
    fn('resetBorderColor', '()',             'Clear the border fill color so the border area inherits the page background.'),
    // Cmd line
    fn('appendCmdLine', '([window,] text)','Append to command bar (or per-window command line when name given)'),
    fn('printCmdLine',  '([window,] text)','Set command bar contents (or per-window command line when name given)'),
    fn('clearCmdLine',  '([window])',      'Clear the command bar (or per-window command line when name given)'),
    fn('getCmdLine',    '([window]) → string', 'Return the current command bar text (or per-window text when name given)'),
    fn('selectCmdLineText', '([window])',      'Select (highlight) all text in the command bar so the next keystroke overtypes it. Only the main bar is wired in mudix.'),
    fn('setCommandBackgroundColor', '([window,] r, g, b [, a])', 'Set the command bar background color (rgba 0..255). Only the main bar is targeted in mudix.'),
    fn('setCommandForegroundColor', '([window,] r, g, b [, a])', 'Set the command bar text color (rgba 0..255). Only the main bar is targeted in mudix.'),
    fn('enableCommandLine',  '(window)',   'Show a per-window command line input below the named userwindow'),
    fn('disableCommandLine', '(window)',   'Hide the per-window command line input on the named userwindow'),
    fn('setCmdLineStyleSheet','([window,] qss)', 'Apply Qt-style QSS to the command line input (per-window or main)'),
    fn('setCmdLineAction',   '([window,] fn [, args...])', 'Bind a function to Enter on the command line. fn may be a function or the name of a global function. With a window arg, targets that userwindow\'s command line.'),
    fn('resetCmdLineAction', '([window])', 'Clear the command-line action binding (per-window or main)'),
    fn('addCmdLineSuggestion',    '(suggestion)', 'Add a tab-completion suggestion to the command bar'),
    fn('removeCmdLineSuggestion', '(suggestion)', 'Remove a previously added tab-completion suggestion'),
    fn('clearCmdLineSuggestions', '()',           'Clear all tab-completion suggestions for the command bar'),
    fn('addCommandLineMenuEvent',    '(uniqueName, event [, displayName])', 'Add a context-menu entry to the command bar; clicking raises event(text)'),
    fn('removeCommandLineMenuEvent', '(uniqueName)',                        'Remove a previously registered command-line menu entry'),
    fn('getCommandLineMenuEvents',   '() → {uniqueName = {event, display}}','Return all registered command-line menu entries'),
    // Packages
    fn('installPackage',        '(path|url)',    'Install a Mudlet .mpackage / .zip / .xml from a VFS path or URL'),
    fn('installPackageFromUrl', '(url)',         'Install a Mudlet package from an http(s):// URL'),
    fn('uninstallPackage',      '(name)',        'Uninstall a previously installed package by name'),
    fn('getPackages',           '() → {name1, name2, ...}', 'Return a 1-indexed list of installed package names'),
    // Modules
    fn('installModule',    '(path)',        'Install a Mudlet module from a VFS path. Plain XML stays in place; zips extract into a managed pkgDir.'),
    fn('uninstallModule',  '(name)',        'Uninstall a module. Unlinks only — the on-disk XML is left in place.'),
    fn('reloadModule',     '(name)',        "Re-parse the module's XML from disk and replace its nodes in the store."),
    fn('syncModule',       '(name)',        "Serialize the module's current in-app state back to its XML file."),
    fn('enableModuleSync', '(name)',        "Auto-sync the module's nodes back to its XML on every edit."),
    fn('disableModuleSync','(name)',        'Stop auto-syncing the module to its XML.'),
    fn('getModuleSync',    '(name) → bool', 'Whether the module has auto-sync enabled.'),
    fn('setModulePriority','(name, n)',     "Set the module's load priority. Negative values load before profile scripts; default 0."),
    fn('getModulePriority','(name) → int',  "Read the module's load priority (default 0)."),
    fn('getModules',       '() → {name1, ...}', 'Return a 1-indexed list of installed module names.'),
    fn('getModuleInfo',    '(name [, key])', "Return the module's manifest as a table, or a single field when key is given."),
    fn('enableModule',     '(name)',        "Mark a module as enabled (it will load on profile open)."),
    fn('disableModule',    '(name)',        "Mark a module as disabled (it will not load on profile open)."),
    fn('isRegisteredModule', '(name) → bool', 'Return true if a module by this name is registered'),
    fn('unzipAsync',       '(zipPath, destDir)', 'Extract a zip into destDir; raises sysUnzipDone / sysUnzipError'),
    // Script toggling
    fn('enableScript',     '(name)',        'Enable a script by name'),
    fn('disableScript',    '(name)',        'Disable a script by name'),
    fn('permScript',       '(name, parent, code) → id',
        'Create a persistent Lua script under parent group (""=root). Returns the new id, or -1 if parent is given but no script group with that name exists.'),
    fn('permRegexTrigger', '(name, parent, regexes, code) → id',
        'Create a persistent regex trigger under parent group (""=root). regexes is a Lua array of regex strings (any-match). Empty regexes creates a trigger group. Returns the new id, or -1 if parent is given but no trigger group with that name exists.'),
    fn('setScript',        '(name, code, [pos]) → true|-1',
        'Replace the source of the pos-th (1-indexed, default 1) script named name. Returns true on success, -1 if no such script exists.'),
    fn('appendScript',     '(scriptName, luaCode, [occurrence]) → true|-1',
        'Append Lua source to an existing script by name (default occurrence=1)'),
    fn('permGroup',        '(name, itemType, [parent]) → id',
        'Create a persistent group. itemType: "alias", "trigger", "timer", "key", "script"'),
    // Trigger toggling
    fn('enableTrigger',    '(name)',        'Enable triggers (and groups) matching name; cascades to children'),
    fn('disableTrigger',   '(name)',        'Disable triggers (and groups) matching name; cascades to children'),
    fn('setTriggerStayOpen', '(name, lines) → bool',
        'Set the chain fire-length on triggers matching name — how many more lines the chain stays open after a match. Pass 0 to close it; positive values extend or shorten an active chain.'),
    fn('enableTimer',      '(name)',        'Enable timers (and groups) matching name; cascades to children'),
    fn('disableTimer',     '(name)',        'Disable timers (and groups) matching name; cascades to children'),
    fn('enableAlias',      '(name)',        'Enable aliases (and groups) matching name; cascades to children'),
    fn('disableAlias',     '(name)',        'Disable aliases (and groups) matching name; cascades to children'),
    fn('enableKey',        '(name) → bool', 'Enable keybindings (and groups) matching name; cascades to children. false if none match.'),
    fn('disableKey',       '(name) → bool', 'Disable keybindings (and groups) matching name; cascades to children. false if none match.'),
    fn('exists',           '(name, type) → number', 'Count items with the given name. type: "alias", "trigger", "timer", "key"/"keybind", "button", "script"'),
    fn('isActive',         '(name|id, type [, checkAncestors]) → number', 'Count active (enabled) items matching the name (1/0 for an id). With checkAncestors=true, every ancestor group must also be enabled. type as for exists.'),
    // Cursor / line inspection
    fn('getCurrentLine',  '([window])',    'Get current trigger line text'),
    fn('getLineNumber',   '([window])',    'Get cursor line number'),
    fn('getLineCount',    '([window])',    'Get total line count'),
    fn('getConsoleBufferSize', '([window]) → linesLimit, batchSize', 'Get a console\'s scrollback line limit and batch-deletion size; nil when the console does not exist'),
    fn('setConsoleBufferSize', '([window,] linesLimit [, batchSize]) → bool', 'Set a console\'s scrollback line limit (and batch-deletion size). Omit window for the main output'),
    fn('getLastLineNumber', '([window])',  'Get line number of the last line in the buffer'),
    fn('getColumnNumber', '([window])',    'Get cursor column'),
    fn('getColumnCount',  '([window]) → number', 'Get the displayable column count of a window — how many monospace characters fit horizontally in the rendered area. Unaffected by setWindowWrap.'),
    fn('getMainConsoleWidth', '() → number', 'Pixel width of the main console text area — monospace cell width × (wrap columns + 1). Wrap columns come from setWindowWrap("main", n), else the live measured column count.'),
    fn('setWindowWrap',   '(window, cols) → bool', 'Set the visual line-wrap width (in monospace columns) for a window (use "main" for the main output). Pass 0 to clear.'),
    fn('getLines',        '([window,] from, to)',  'Get range of lines as table'),
    fn('isPrompt',        '()',            'True if current line is a MUD prompt'),
    fn('moveCursorUp',    '([window])',    'Move cursor up one line'),
    fn('moveCursorDown',  '([window])',    'Move cursor down one line'),
    fn('moveCursor',      '([window,] x, y)',              'Move cursor to position'),
    fn('selectString',    '([window,] text, occurrence)', 'Select Nth occurrence of text on current line; returns column index or -1'),
    fn('selectSection',   '([window,] from, length)',     'Select text by column position and length'),
    fn('selectCurrentLine','([window])',                   'Select the entire current line. Equivalent to selectSection(0, #getCurrentLine())'),
    fn('deselect',        '([window])',                   'Clear the current selection'),
    fn('getSelection',    '([window]) → text, start, length',
        'Returns the current selection: text, 0-based start column, and length. Returns false, "no selection" when nothing is selected.'),
    fn('getFgColor',      '([window]) → r, g, b',
        'Foreground RGB (0..255) at the current selection start. Returns no values when there is no selection; falls back to the profile default text color when the segment carries no explicit color.'),
    fn('getBgColor',      '([window]) → r, g, b',
        'Background RGB (0..255) at the current selection start. Returns no values when there is no selection; falls back to the profile default background when the segment carries no explicit color.'),
    fn('getTextFormat',   '([window]) → table',
        'Display attributes of the character at the current selection start: bold, italic, underline, strikeout, reverse, overline, concealed (booleans), alternateFont (number), blinking ("none"/"slow"/"fast"), and foreground/background as {r, g, b}. overline/concealed/alternateFont report Mudlet "off" values (no equivalent channel). Returns nil, errMsg when there is no selection.'),
    // Timers
    fn('tempTimer',      '(seconds, fn, repeat?)', 'Create a timer (one-shot or repeating)'),
    fn('killTimer',      '(id)',           'Cancel a timer'),
    // Aliases
    fn('tempAlias',      '(pattern, fn) → id', 'Create a temporary alias'),
    fn('killAlias',      '(id)',           'Remove an alias'),
    // Triggers
    fn('tempTrigger',    '(pattern, fn, expirationCount?) → id', 'Create a temporary trigger. expirationCount: positive N auto-kills after N fires; omitted/<=0 = unlimited'),
    fn('tempRegexTrigger','(regex, fn, expirationCount?) → id', 'Create a temporary regex trigger. expirationCount: positive N auto-kills after N fires; omitted/<=0 = unlimited'),
    fn('tempExactMatchTrigger','(line, fn, expirationCount?) → id', 'Create a temporary trigger that fires when the line is exactly equal to the pattern. expirationCount: positive N auto-kills after N fires; omitted/<=0 = unlimited'),
    fn('tempBeginOfLineTrigger','(prefix, fn, expirationCount?) → id', 'Create a temporary trigger that fires when the line starts with the given literal prefix (NOT regex — no ^ anchor needed). Fast prefix check. expirationCount: positive N auto-kills after N fires; omitted/<=0 = unlimited'),
    fn('tempPromptTrigger','(fn, expirationCount?) → id', 'Create a temporary trigger that fires on every server prompt line (no pattern). expirationCount: positive N auto-kills after N fires; omitted/<=0 = unlimited'),
    fn('killTrigger',    '(id)',           'Remove a trigger'),
    fn('tempLineTrigger','(linesAhead, count, code)', 'Trigger N lines ahead'),
    // Keys
    fn('tempKey',        '(modifier, key, fn) → id',  'Create a temporary keybinding. modifier: Qt bitflag (0=none, 67108864=Ctrl, 33554432=Shift, 134217728=Alt). key: Qt::Key int or web code string'),
    fn('killKey',        '(id)',                       'Remove a keybinding'),
    // Named triggers / timers / event handlers
    fn('registerNamedTrigger',      '(userName, triggerName, substring, fn [, expireAfter]) → bool', 'Register a named substring trigger keyed by (userName, triggerName)'),
    fn('registerNamedRegexTrigger', '(userName, triggerName, regex, fn [, expireAfter]) → bool',     'Register a named regex trigger keyed by (userName, triggerName)'),
    fn('registerNamedTimer',        '(userName, timerName, time, fn [, repeating]) → bool',          'Register a named timer keyed by (userName, timerName)'),
    fn('registerNamedEventHandler', '(userName, handlerName, eventName, fn [, oneShot]) → bool',     'Register a named event handler keyed by (userName, handlerName)'),
    fn('deleteNamedTrigger',        '(userName, triggerName) → bool',  'Delete a named trigger'),
    fn('deleteNamedTimer',          '(userName, timerName) → bool',    'Delete a named timer'),
    fn('deleteNamedEventHandler',   '(userName, handlerName) → bool',  'Delete a named event handler'),
    fn('deleteAllNamedTriggers',    '(userName) → bool',               'Delete all named triggers for a user'),
    fn('deleteAllNamedTimers',      '(userName) → bool',               'Delete all named timers for a user'),
    fn('deleteAllNamedEventHandlers','(userName) → bool',              'Delete all named event handlers for a user'),
    fn('stopNamedTrigger',          '(userName, triggerName) → bool',  'Disable (without deleting) a named trigger'),
    fn('stopNamedTimer',            '(userName, timerName) → bool',    'Disable (without deleting) a named timer'),
    fn('stopNamedEventHandler',     '(userName, handlerName) → bool',  'Disable (without deleting) a named event handler'),
    fn('stopAllNamedTriggers',      '(userName) → bool',               'Disable all named triggers for a user'),
    fn('stopAllNamedTimers',        '(userName) → bool',               'Disable all named timers for a user'),
    fn('stopAllNamedEventHandlers', '(userName) → bool',               'Disable all named event handlers for a user'),
    fn('resumeNamedTrigger',        '(userName, triggerName) → bool',  'Re-enable a previously stopped named trigger'),
    fn('resumeNamedTimer',          '(userName, timerName) → bool',    'Re-enable a previously stopped named timer'),
    fn('resumeNamedEventHandler',   '(userName, handlerName) → bool',  'Re-enable a previously stopped named event handler'),
    fn('getNamedTriggers',          '(userName) → {names...}',         'List all named triggers for a user'),
    fn('getNamedTimers',            '(userName) → {names...}',         'List all named timers for a user'),
    fn('getNamedEventHandlers',     '(userName) → {names...}',         'List all named event handlers for a user'),
    // Speedwalk
    fn('speedwalk',       '(dirString [, backwards, delay, show])',     'Walk a direction-string path (e.g. "3nW2e"); optionally backwards, with per-step delay (s) and visible commands'),
    fn('pauseSpeedwalk',  '()',                                          'Pause an active speedwalk'),
    fn('resumeSpeedwalk', '()',                                          'Resume a paused speedwalk'),
    fn('stopSpeedwalk',   '()',                                          'Stop an active speedwalk'),
    // Persistent variables
    fn('saveVars',        '()',          'Save persistent variables (the `_G.varname = ...; remember("varname")` set) to profile storage'),
    fn('loadVars',        '()',          'Load persistent variables saved by saveVars()'),
    fn('remember',        '(varname)',   'Mark a global variable name to be persisted across sessions'),
    // Timeframes
    fn('timeframe',     '(vname, true_time, nil_time, ...)', 'Schedule a boolean flag to flip true at true_time and back to nil at nil_time, repeating daily'),
    fn('killtimeframe', '(vname)',                            'Cancel a previously-scheduled timeframe'),
    // Misc utilities
    fn('mudletOlderThan',  '(major [, minor, patch]) → bool', 'True if Mudlet (compat shim) reports a version older than the given one'),
    fn('shms',             '(seconds [, returnAsString])',    'Convert seconds to hours/minutes/seconds — returns h,m,s or "hh:mm:ss"'),
    fn('getConfig',        '([option]) → value',              'Get a config option (no arg returns the entire config table)'),
    fn('setConfig',        '(option, value)',                 'Set a config option'),
    fn('translateTable',   '(directions [, languageCode])',   'Translate a list of direction strings using the built-in translation table'),
    fn('spairs',           '(t [, sortFn]) → iterator',       'Sorted-pairs iterator: like pairs but keys are visited in sorted order'),
    fn('selectAll',        '([window])',                      'Select the entire content of the current line/window'),
    fn('openMudletHomeDir','()',                              'Open the Mudlet home directory in the OS file manager (no-op in the web client)'),
    // File system
    fn('getMudixProfilePath', '() → string',        'Returns the VFS profile root path for this connection'),
    fn('getMudletHomeDir',   '() → string',        'Mudlet-compatible alias for getMudixProfilePath()'),
    fn('getMudletVersion',   '([mode]) → version', 'Mudlet version. No arg → {major, minor, revision, build} table. "string" → "X.Y.Z". "major"/"minor"/"revision"/"build" → field. "table" → major, minor, revision as 3 return values'),
    fn('getConnectionInfo',  '() → host, port, connected', 'Active connection details: host string, port number, and whether the session is currently connected. For mud-mode connections these are the configured host/port; for raw websocket connections they are parsed from the endpoint URL.'),
    fn('announce',           '(text [, processing])', 'Send text to assistive technology via an ARIA live region. processing controls politeness: "importantall"/"importantmostrecent" → assertive, anything else → polite.'),
    fn('showNotification',   '(title [, content [, expirySeconds]])', 'Show a desktop notification via the Web Notifications API (requests permission on first use). content defaults to title; expirySeconds auto-closes it. Always returns true.'),
    fn('getEpoch',           '() → number',        'Seconds since the Unix epoch (1970-01-01 UTC) with millisecond precision'),
    fn('getOS',              '() → string',        'Operating system the client is running on, sniffed from the user agent: "windows", "mac", "linux", "freebsd"/"openbsd"/"netbsd", or "unknown". Useful for OS-specific scripts (e.g. mac vs. windows keybinding hints).'),
    fn('getWindowsCodepage', '() → string',        'Active ANSI code page. The browser VFS is always UTF-8, so this returns "65001" (the UTF-8 code page) on every platform — which makes the bundled utf8_filenames.lua correctly skip legacy-ANSI filename transcoding.'),
    // Stopwatches — high-resolution (performance.now) timers by id or name
    fn('createStopWatch',    '([name] [, autostart]) → id|false', 'Create a stopwatch and return its id. A string name (must be unique) defaults autostart off; pass a boolean to control autostart (an unnamed watch autostarts by default). false if the name is taken.'),
    fn('startStopWatch',     '(id|name [, resetAndRestart]) → bool', 'Start/resume a stopwatch. A bare numeric id resets to zero and restarts (legacy behaviour); pass false as 2nd arg to resume instead. The name form always just resumes. false if not found.'),
    fn('stopStopWatch',      '(id|name) → seconds|false', 'Pause a stopwatch and return its elapsed time in seconds. false if not found.'),
    fn('getStopWatchTime',   '(id|name) → seconds|false', 'Elapsed time in seconds, without stopping the watch. false if not found.'),
    fn('resetStopWatch',     '(id|name) → bool', 'Reset elapsed time to zero. A running watch keeps running from zero. false if not found.'),
    fn('adjustStopWatch',    '(id|name, seconds) → bool', 'Add seconds (may be negative) to a stopwatch’s elapsed time. false if not found.'),
    fn('deleteStopWatch',    '(id|name) → bool', 'Delete a stopwatch. false if not found.'),
    fn('getStopWatches',     '() → table', 'Table of all stopwatches keyed by id: { name, isRunning, isPersistent, elapsedTime = {negative, days, hours, minutes, seconds, milliSeconds, decimalSeconds} }.'),
    fn('setStopWatchPersistence', '(id|name, state) → bool', 'Mark a stopwatch persistent. Persistent watches are saved to localStorage (per connection) and restored on the next load — a running one keeps counting across reloads, including time the client was closed. false if not found.'),
    fn('getTime',            '([asString [, format]]) → table|string', 'Current local time. Default → table {year,month,day,hour,min,sec,msec}. With asString=true → string formatted via Qt-style tokens (default "hh:mm:ss.zzz"): yyyy/yy, MMMM/MMM/MM/M, dddd/ddd/dd/d, HH/H (24h), hh/h (12h when AP/ap in format), mm/m, ss/s, zzz/z, AP/A/ap/a.'),
    fn('saveProfile',        '([location]) → true, path', 'Force pending profile data (VFS files, SQL snapshots) through to durable storage. zustand state auto-saves on every change so this is a no-op for triggers/aliases/scripts; useful after io.open/db: writes. The optional location arg is accepted for Mudlet compatibility but ignored.'),
    fn('loadRawFile',        '(path) → string',    'Read entire file from VFS and return its contents'),
    fn('loadfile',           '(filename)',          'Load a Lua file from VFS'),
    fn('dofile',             '(filename)',          'Load and execute a Lua file from VFS'),
    fn('addFileWatch',       '(path) → bool',       'Watch a VFS file or directory; sysPathChanged(path) fires when Lua mutates the file (or any descendant of a watched directory). Path must exist. Browser has no native FS notifier, so external changes to a linked folder require ProfileVFS.resync() before they fire.'),
    fn('removeFileWatch',    '(path) → bool',       'Stop watching a path previously registered with addFileWatch. Returns false if the path was not watched.'),
    // Events
    fn('raiseEvent',                    '(name, ...)',       'Fire a named event'),
    fn('registerAnonymousEventHandler', '(name, fn) → id',  'Register an event handler, returns an ID'),
    fn('killAnonymousEventHandler',     '(id) → bool',       'Remove an event handler by ID'),
    // Formatting
    fn('setUnderline',      '(bool)',                          'Toggle underline text formatting'),
    fn('setReverse',        '([window,] bool)',                'Toggle reverse-video (swaps foreground/background) on the current pen and selection'),
    fn('setTextFormat',     '(windowName, r1, g1, b1, r2, g2, b2, bold, underline, italics, [strikeout], [overline], [reverse], [blinkMode]) → bool',
        'Set pen state in one call. r1/g1/b1 is BACKGROUND, r2/g2/b2 is FOREGROUND (Mudlet quirk). Booleans accept true/false or 1/0. blinkMode is "none"/"slow"/"fast". overline is accepted but a no-op (no overline channel). windowName "" or "main" targets the main console. Returns false when the named window does not exist.'),
    fn('moveCursorEnd',     '([windowName])',                  'Move cursor to end of current line'),
    fn('openWebPage',       '(url)',                           'Open a URL in the browser'),
    fn('openUrl',           '(url) → bool',                    'Open a URL in a new tab. A `file:` prefix opens the path in the VFS file browser (e.g. openUrl("file:" .. getMudletHomeDir())).'),
    // Links
    fn('echoLink',          '([window,] text, cmd, tooltip [, useCurrentFmt])',      'Echo clickable link text'),
    fn('cechoLink',         '([window,] colorText, cmd, tooltip [, useCurrentFmt])', 'Echo Mudlet-color-tag link text'),
    fn('dechoLink',         '([window,] colorText, cmd, tooltip [, useCurrentFmt])', 'Echo decimal-RGB link text'),
    fn('hechoLink',         '([window,] colorText, cmd, tooltip [, useCurrentFmt])', 'Echo hex-RGB link text'),
    fn('insertLink',        '([window,] text, cmd, tooltip [, useCurrentFmt])',      'Insert a clickable link at the trigger cursor'),
    fn('cinsertLink',       '([window,] text, cmd, tooltip [, useCurrentFmt])',      'Insert a Mudlet-color-tag link at the trigger cursor'),
    fn('dinsertLink',       '([window,] text, cmd, tooltip [, useCurrentFmt])',      'Insert a decimal-RGB link at the trigger cursor'),
    fn('hinsertLink',       '([window,] text, cmd, tooltip [, useCurrentFmt])',      'Insert a hex-RGB link at the trigger cursor'),
    fn('cechoPopup',        '([window,] text, {commands}, {hints} [, useCurrentFmt])', 'Echo Mudlet-color-tag text with a right-click popup of commands/hints'),
    fn('dechoPopup',        '([window,] text, {commands}, {hints} [, useCurrentFmt])', 'Echo decimal-RGB text with a right-click popup of commands/hints'),
    fn('hechoPopup',        '([window,] text, {commands}, {hints} [, useCurrentFmt])', 'Echo hex-RGB text with a right-click popup of commands/hints'),
    fn('echoPopup',         '([window,] text, {commands}, {hints})', 'Echo text carrying a right-click popup menu of commands (labelled by hints)'),
    fn('insertPopup',       '([window,] text, {commands}, {hints})', 'Insert text at the cursor carrying a right-click popup menu of commands'),
    fn('cinsertPopup',      '([window,] text, {commands}, {hints} [, useCurrentFmt])', 'Insert Mudlet-color-tag text at cursor with a right-click popup'),
    fn('dinsertPopup',      '([window,] text, {commands}, {hints} [, useCurrentFmt])', 'Insert decimal-RGB text at cursor with a right-click popup'),
    fn('hinsertPopup',      '([window,] text, {commands}, {hints} [, useCurrentFmt])', 'Insert hex-RGB text at cursor with a right-click popup'),
    fn('setLink',           '([window,] cmd, tooltip)',         'Apply a clickable link to the current selection. cmd is Lua code or a function.'),
    fn('setPopup',          '([window,] {commands}, {hints})',  'Attach a right-click popup menu (commands labelled by hints) to the current selection'),
    // Map
    fn('centerview',           '(roomId)',                         'Center map on a room'),
    fn('getPlayerRoom',        '() → id|nil',                      'Get the player\'s current room id (set by centerview); nil when unset or the room no longer exists'),
    fn('loadMap',              '([location]) → bool',              'Load a Mudlet binary `.dat` map from a VFS path; persists to IndexedDB and re-renders the panel. With no path, reloads from already-stored bytes. Returns false on a missing/unreadable/unparseable file.'),
    fn('saveMap',              '([location]) → bool',              'Serialise the current map to Mudlet binary `.dat` format and persist it to the connection\'s IndexedDB slot (the default profile location). With a path, also writes the bytes to that VFS path. Returns false on serialisation or write failure.'),
    fn('saveWindowLayout',     '() → bool',                        'Capture the current window layout (positions, sizes, dock state, dock-area extents) into a per-connection snapshot in persistent storage. Restore later with loadWindowLayout(). Returns false when no connection is active.'),
    fn('loadWindowLayout',     '() → bool',                        'Restore the most recently saved window layout for this connection — re-positions live windows and reopens saved-visible windows that are currently closed. Returns false when no snapshot has been saved yet.'),
    fn('getRoomIDbyHash',      '(hash) → id|nil',                 'Look up a room ID by its hash string'),
    fn('createRoomID',         '() → id',                         'Get the next available room ID'),
    fn('addRoom',              '(id) → bool',                     'Create a new room'),
    fn('deleteRoom',           '(id)',                             'Delete a room'),
    fn('roomExists',           '(id) → bool',                     'Check if a room exists'),
    fn('getRoomName',          '(id) → name',                     'Get a room name'),
    fn('setRoomName',          '(id, name)',                       'Set a room name'),
    fn('getRoomArea',          '(id) → areaId',                   'Get the area a room belongs to'),
    fn('setRoomArea',          '(id, areaId)',                     'Move a room to an area'),
    fn('getRoomCoordinates',   '(id) → x, y, z',                  'Get room coordinates'),
    fn('setRoomCoordinates',   '(id, x, y, z)',                    'Set room coordinates'),
    fn('getRoomsByPosition',   '(areaId, x, y, z) → {0=id,...}',  'Get rooms at a position'),
    fn('setRoomIDbyHash',      '(id, hash)',                       'Set the hash for a room'),
    fn('getRoomHashByID',      '(id) → hash|nil',                  'Get the hash for a room'),
    fn('getRoomExits',         '(id) → {dir=toId}',               'Get room exits'),
    fn('getPath',              '(from, to) → bool[, totalWeight | -1, errMsg]',
       "A* shortest path on the map graph. On success returns (true, totalWeight) and populates speedWalkPath / speedWalkDir / speedWalkWeight (1-indexed, excluding the start room). On failure returns (false, -1, errMsg); on argument-validation failure returns (false, errMsg). Honors per-exit weights, target-room weights, locked rooms, and locked stock exits."),
    fn('setExit',              '(from, to, dir)',                   'Set an exit (dir 1-12, to=-1 removes)'),
    fn('getExitStubs',         '(id) → {dir,...}',                 'Get stub direction numbers (0-indexed table)'),
    fn('getExitStubs1',        '(id) → {dir,...}',                 'Get stub direction numbers (1-indexed table)'),
    fn('setExitStub',          '(id, dir, bool)',                   'Set or clear an exit stub'),
    fn('addSpecialExit',       '(from, to, cmd)',                   'Add a special/portal exit'),
    fn('removeSpecialExit',    '(from, cmd)',                       'Remove a special exit'),
    fn('getSpecialExitsSwap',  '(id) → {cmd=toId}',               'Get special exits (cmd→toId)'),
    fn('getSpecialExits',      '(id [, listAllExits]) → {toId={cmd="0"|"1"}}',
       'Get special exits keyed by destination room id; inner value is command→lock state ("1"=locked). With listAllExits=false (default), only the lowest-weight command to each room is listed; pass true to list every command.'),
    fn('getExitWeights',       '(id) → {exit=weight}',             'Get per-exit weight overrides; keys are short direction names ("n"/"ne"/…) or special-exit commands'),
    fn('setExitWeight',        '(id, exitCommand, weight) → bool',  'Override one exit\'s pathfinding weight. exitCommand is a stock direction (1-12 or name) or a special-exit command. weight 0 resets to the destination room\'s weight'),
    fn('lockRoom',             '(id, lockIfTrue) → bool',           'Lock/unlock a room so pathfinding routes around it'),
    fn('roomLocked',           '(id) → bool|nil',                   'Whether a room is locked; nil when the room does not exist'),
    fn('getRoomWeight',        '(id) → weight',                     'Get a room\'s pathfinding weight (cost to enter)'),
    fn('setRoomWeight',        '(id, weight) → bool',               'Set a room\'s pathfinding weight (0 or more)'),
    fn('getCustomLines',       '(id) → {dir={attributes={color,style,arrow},points={[0]={x,y,z},...}}} | nil',
       "Get the room's custom exit lines. Returns nil when the room doesn't exist, an empty table when there are no custom lines. Points are 0-indexed; style is one of 'solid line', 'dash line', 'dot line', 'dash dot line', 'dash dot dot line'."),
    fn('getDoors',             '(id) → {dir=val}',                 'Get doors on a room'),
    fn('setDoor',              '(id, dir, val)',                    'Set a door (0=none,1=open,2=closed,3=locked)'),
    fn('getRoomUserData',      '(id, key) → value',                'Get custom room data'),
    fn('setRoomUserData',      '(id, key, value)',                  'Set custom room data'),
    fn('getRoomUserDataKeys',  '(id) → {key1, key2, …} | nil',     'Get all user-data keys stored on the room; returns an empty table when the room has no data, or nil when the room does not exist'),
    fn('getMapUserData',       '(key) → value | (false, errMsg)',  "Get a value from the map's free-form user-data dict; (false, errMsg) when the key isn't set"),
    fn('setMapUserData',       '(key, value) → true',              "Set a value in the map's free-form user-data dict"),
    fn('clearMapUserData',     '() → bool',                        'Wipe the entire map user-data dict; returns true if anything was cleared'),
    fn('clearMapUserDataItem', '(key) → bool',                     'Remove a single key from map user-data; returns true if it existed'),
    fn('getAllMapUserData',    '() → {key=value}',                 'Get a snapshot of the entire map user-data dict'),
    fn('getRoomEnv',           '(id) → envId',                     'Get room environment'),
    fn('setRoomEnv',           '(id, envId)',                       'Set room environment'),
    fn('getRoomChar',          '(id) → char',                      'Get room symbol/character'),
    fn('setRoomChar',          '(id, char)',                        'Set room symbol/character'),
    fn('addAreaName',          '(name) → areaId',                  'Create a new area'),
    fn('deleteArea',           '(areaId)',                          'Delete an area and its rooms'),
    fn('getAreaTable',         '() → {name=id}',                   'Get all areas (name→id)'),
    fn('getRoomAreaName',      '(areaId) → name',                  'Get an area name'),
    fn('setAreaName',          '(areaId, name)',                    'Rename an area'),
    fn('getAreaRooms',         '(areaId) → {0=id,...}',            'Get all room IDs in an area'),
    fn('getRooms',             '() → {id=name}',                   'Get all rooms in the map (id→name)'),
    fn('getMapLabels',         '(areaID) → {labelID=labelText}',   'Get all map labels in an area, keyed by label id'),
    fn('getMapLabel',          '(areaID, labelID|labelText) → info|{labelID=info}',
       'Get a map label by id (returns a properties table: X,Y,Z,Width,Height,Text,Pixmap,OnTop,Scaling,Temporary,FgColor,BgColor) or by text (returns matches keyed by label id). Returns (false, errMsg) when the area is missing or the labelID is unknown.'),
    fn('addMapEvent',          '(uniqueName, eventName [, parent [, displayName [, ...args]]]) → bool',
       "Add an entry to the map's right-click context menu. On click, raises eventName with the right-clicked roomId as the first arg, followed by your extra args. Pass another entry's uniqueName as `parent` to nest as a submenu."),
    fn('removeMapEvent',       '(uniqueName) → bool',              'Remove a previously registered map context-menu entry. Returns true if the entry existed.'),
    fn('getMapEvents',         '() → {uniqueName = {event,parent,display,args}}',
       'Get all registered map context-menu entries.'),
    fn('registerMapInfo',      '(label, function) → true',
       'Register a callback that contributes a custom text line to the mapper widget. The callback receives (roomId, selectionSize, areaId, displayedAreaId) and returns (text, isBold?, isItalic?, r?, g?, b?). New contributors land disabled — call enableMapInfo(label) to show. Re-registering the same label replaces the prior callback.'),
    fn('killMapInfo',          '(label) → true | (false, errMsg)',
       'Remove a registerMapInfo contributor entirely.'),
    fn('enableMapInfo',        '(label) → true | (false, errMsg)',
       'Show a registered map info contributor in the mapper widget.'),
    fn('disableMapInfo',       '(label) → true | (false, errMsg)',
       'Hide a registered map info contributor without removing it.'),
    fn('setCustomEnvColor',    '(envID, r, g, b [, a])',           'Set a custom environment color used to paint rooms whose env matches envID'),
    fn('getCustomEnvColor',    '(envID) → r, g, b, a | nil',       'Return the registered RGBA for a custom env, or nil if none'),
    fn('highlightRoom',        '(id, r1, g1, b1, r2, g2, b2, radius [, a1, a2]) → bool',
       'Highlight a room with an overlay color, overriding its environment color. mudix paints with color1 (alpha a1) — color2/radius round-trip via getRoomHighlights but are not visualized.'),
    fn('unHighlightRoom',      '(id) → bool',                      'Remove a previously set room highlight; returns true if one was active.'),
    fn('setRoomNameOffset',    '(id, dx, dy)',                     'Offset the displayed room name label for a room by (dx, dy) pixels'),
    fn('getRoomNameOffset',    '(id) → dx, dy',                    'Get the room-name label offset for a room'),
    fn('setRoomNameVisible',   '(id, bool)',                       'Show or hide the room name label for a room'),
    // Gauges
    fn('createGauge',         '([window,] name, w, h, x, y, text, r, g, b [, orientation])',
       'Create a gauge overlay. Color may also be a name. Orientation: horizontal (default), vertical, goofy (right→left), batty (top→bottom).'),
    fn('setGauge',            '(name, current, max [, text])',     'Set gauge fill ratio (current/max) and optional text'),
    fn('setGaugeText',        '(name, text [, r, g, b])',          'Set gauge text. Color args optional; accepts r,g,b or color name'),
    fn('moveGauge',           '(name, x, y)',                      'Move a gauge to a new position'),
    fn('resizeGauge',         '(name, width, height)',             'Resize a gauge'),
    fn('showGauge',           '(name)',                            'Show a hidden gauge'),
    fn('hideGauge',           '(name)',                            'Hide a gauge'),
    fn('destroyGauge',        '(name)',                            'Destroy a gauge'),
    fn('setGaugeStyleSheet',  '(name, css [, cssBack [, cssText]])', 'Apply CSS to gauge layers (front, back, text)'),
    fn('setGaugeToolTip',     '(name, text [, duration])', 'Set a gauge tooltip'),
    fn('resetGaugeToolTip',   '(name)',                     'Clear a gauge tooltip'),
    fn('setGaugeWindow',      '(windowName, gaugeName, x, y)', 'Move a gauge to a different parent window at (x, y)'),
    fn('enableGaugeClickthrough',  '(name)',                'Make a gauge pass mouse events through to whatever is underneath'),
    fn('disableGaugeClickthrough', '(name)',                'Re-enable mouse interception on a gauge'),
    // Labels
    fn('createLabel',         '([window,] name, x, y, w, h, fillBackground [, clickThrough]) → bool',
       'Create a positioned overlay label on the parent window (default "main"). fillBackground and clickThrough accept 0/1 or true/false. Returns true on success, false if a label with that name already exists.'),
    fn('deleteLabel',         '(name) → bool',                       'Destroy a label by name. Returns true if the label existed.'),
    fn('setLabelStyleSheet',  '(name, css)',                         'Apply a Qt-style CSS string to a label. Background-color/border/font-size/etc. translate; Qt-specific selectors are dropped.'),
    fn('getLabelStyleSheet',  '(name) → css',                        'Get the Qt-style CSS string last applied to a label (empty string when none).'),
    fn('setLabelClickCallback','(name, fn)',
       'Install a click handler on a label. fn may be a function or a Lua code string (compiled with loadstring). Replacing the callback leaks the prior closure in the registry.'),
    fn('setLabelToolTip',     '(name, text [, duration])',           'Set a tooltip on a label. duration is accepted for Mudlet compatibility but ignored (HTML title attribute has no per-tooltip duration).'),
    fn('resetLabelToolTip',   '(name)',                              'Clear a label tooltip.'),
    fn('enableClickthrough',  '(name)',                              'Make a label pass mouse events through to whatever is underneath.'),
    fn('disableClickthrough', '(name)',                              'Re-enable mouse interception on a label.'),
    fn('raiseLabel',          '(name)',                              'Raise a label above all other labels (z-index).'),
    fn('lowerLabel',          '(name)',                              'Lower a label below all other labels (z-index).'),
    fn('setLabelCursor',      '(name, shape)',                       'Set the mouse cursor over a label. shape is a Qt::CursorShape int (or string name; see mudlet.cursor). -1 resets.'),
    fn('resetLabelCursor',    '(name)',                              'Restore the default cursor on a label.'),
    fn('setLabelCustomCursor','(name, cursorPath [, hotX, hotY])',   'Set a label cursor to a custom image. cursorPath resolves against the package VFS; hotX/hotY are the hotspot in pixels (default 0,0).'),
    // Sounds
    fn('playSoundFile',       '(filename [, volume]) | ({name=..., volume=..., fadein=..., fadeout=..., start=..., loops=..., key=..., tag=...})',
       'Play a sound effect. Filename resolves against the profile VFS (e.g. "media/hit.wav") or may be an absolute http(s):// URL. Volume 0..100; loops -1=infinite; fadein/fadeout/start in ms. Browser audio unlocks after the first user gesture; before that, playback is queued until unlock.'),
    fn('playMusicFile',       '({name=..., volume=..., fadein=..., fadeout=..., start=..., loops=..., key=..., tag=..., ["continue"]=bool})',
       'Play a music track. One track per key (or per name when no key) — a second call replaces it. With continue=true the call is a no-op if a matching track is already playing.'),
    fn('loadSoundFile',       '(name [, url]) | ({name=...})',       'Preload (decode + cache) a sound so the first playSoundFile has no decode latency. name resolves against the profile VFS or may be an http(s):// URL.'),
    fn('getPlayingSounds',    '([{name=..., key=..., tag=...}] | name [, key, tag]) → {{name, key, tag, volume}, ...}', 'Return the currently playing sound effects, optionally filtered by name/key/tag. Volume is on the 0..100 scale.'),
    fn('stopSounds',          '()',                                  'Stop all currently playing sound effects (does not stop music).'),
    fn('stopMusic',           '([{name=..., key=..., tag=..., fadeout=...}])',
       'Stop matching music tracks. With no args, stops all music. fadeout (ms) overrides the per-track fadeout for this call.'),
    // Text-to-speech (Web Speech API). Raises tts* state/change events.
    fn('ttsSpeak',            '(text)',
       'Speak text immediately via the browser TTS engine, interrupting anything in progress. The queue resumes once this finishes. Angle brackets are stripped.'),
    fn('ttsQueue',            '(text [, index])',
       'Append text to the speech queue, or insert it at 1-based index. Starts playback if idle. Raises ttsSpeechQueued(text, index).'),
    fn('ttsClearQueue',       '([index])',
       'Clear the whole pending queue, or just the item at 1-based index (false if out of bounds). Does not stop the current utterance.'),
    fn('ttsGetQueue',         '([index]) → text | {texts} | false',
       'With an index, the queued text at that 1-based position (false if out of bounds); without one, the whole queue as a 1-based table.'),
    fn('ttsSkip',             '()',                                  'Stop the current utterance and advance to the next queued one.'),
    fn('ttsPause',            '()',                                  'Pause the current utterance.'),
    fn('ttsResume',           '()',                                  'Resume a paused utterance.'),
    fn('ttsGetState',         '() → state',
       'Current TTS state: "ttsSpeechReady" | "ttsSpeechStarted" | "ttsSpeechPaused" | "ttsSpeechError" | "ttsUnknownState".'),
    fn('ttsGetCurrentLine',   '() → text | nil, reason',             'The text currently being spoken, or (nil, reason) when idle or errored.'),
    fn('ttsGetVoices',        '() → {names}',                        'A 1-based table of available voice names from the browser TTS engine.'),
    fn('ttsGetCurrentVoice',  '() → name',                           'The selected voice name (falls back to the engine default when none was set).'),
    fn('ttsSetVoiceByName',   '(name) → bool',                       'Select a voice by name. Returns false if no voice matches. Raises ttsVoiceChanged.'),
    fn('ttsSetVoiceByIndex',  '(index) → bool',                      'Select a voice by 1-based index into ttsGetVoices(). Returns false if out of bounds. Raises ttsVoiceChanged.'),
    fn('ttsSetRate',          '(rate)',                              'Set speaking rate, clamped to -1..1 (0 = normal). Raises ttsRateChanged.'),
    fn('ttsGetRate',          '() → rate',                           'Current speaking rate (-1..1).'),
    fn('ttsSetPitch',         '(pitch)',                             'Set pitch, clamped to -1..1 (0 = normal). Raises ttsPitchChanged.'),
    fn('ttsGetPitch',         '() → pitch',                          'Current pitch (-1..1).'),
    fn('ttsSetVolume',        '(volume)',                            'Set volume, clamped to 0..1 (1 = full). Raises ttsVolumeChanged.'),
    fn('ttsGetVolume',        '() → volume',                         'Current volume (0..1).'),
    // rex
    ns('rex', 'PCRE-compatible regex module: rex.match(), rex.find(), rex.new()'),
    // Globals / tables
    variable('gmcp',         'GMCP state table — auto-populated from server packets'),
    variable('msdp',         'MSDP state table — auto-populated from server packets'),
    variable('matches',      'Regex captures in trigger/alias context: [full, cap1, cap2, ...]'),
    variable('line',         'Current trigger line text'),
    variable('multimatches', 'Multiline trigger captures'),
    variable('color_table',  'Mudlet color table: { colorName = {r, g, b} }'),
    variable('speedWalkPath',   'getPath result: 1-indexed list of room IDs along the path (excludes the start room). Reset on every getPath call.'),
    variable('speedWalkDir',    'getPath result: 1-indexed list of direction strings ("n"/"ne"/"up"/special-exit cmd) taken at each step. Reset on every getPath call.'),
    variable('speedWalkWeight', 'getPath result: 1-indexed list of step costs (target room weights or per-exit weight overrides). Reset on every getPath call.'),
];

// ── Global completions (everything available at top level) ────────────────────

const GLOBAL_COMPLETIONS: Completion[] = [
    ...LUA_KEYWORDS,
    ...LUA_GLOBALS,
    ...MUDLET_GLOBALS,
];

// ── Reference groups (for the "?" reference panel) ────────────────────────────
// These map dotted prefixes onto the underlying completion arrays so the
// reference UI stays in sync with autocomplete without duplicating data.

export interface ReferenceGroup {
    title:   string;        // e.g. "string", "table", "globals"
    prefix:  string;        // dotted prefix prepended when inserting (e.g. "string.")
    entries: Completion[];
}

export const REFERENCE_GROUPS: ReferenceGroup[] = [
    { title: 'Mudlet globals',  prefix: '',                entries: MUDLET_GLOBALS },
    { title: 'Lua globals',     prefix: '',                entries: LUA_GLOBALS    },
    { title: 'string',          prefix: 'string.',         entries: STRING_EXT     },
    { title: 'table',           prefix: 'table.',          entries: TABLE_EXT      },
    { title: 'math',            prefix: 'math.',           entries: MATH_EXT       },
    { title: 'io',              prefix: 'io.',             entries: IO_COMPLETIONS },
    { title: 'lfs',             prefix: 'lfs.',            entries: LFS_COMPLETIONS },
];

// ── Hover lookup map: full dotted name → completion entry ────────────────────

export const HOVER_MAP = new Map<string, Completion>([
    // Global scope (bare names)
    ...[...LUA_KEYWORDS, ...LUA_GLOBALS, ...MUDLET_GLOBALS].map(
        c => [c.label, c] as [string, Completion]
    ),
    // Namespaced symbols
    ...IO_COMPLETIONS .map(c => [`io.${c.label}`,             c] as [string, Completion]),
    ...LFS_COMPLETIONS.map(c => [`lfs.${c.label}`,            c] as [string, Completion]),
    ...STRING_EXT    .map(c => [`string.${c.label}`,         c] as [string, Completion]),
    ...TABLE_EXT     .map(c => [`table.${c.label}`,          c] as [string, Completion]),
    ...MATH_EXT      .map(c => [`math.${c.label}`,           c] as [string, Completion]),
]);

// ── Namespace map: prefix → completions for that sub-namespace ────────────────
// Order matters: more specific prefixes must come first.

const NAMESPACE_MAP: Array<[string, Completion[]]> = [
    ['io.',     IO_COMPLETIONS],
    ['lfs.',    LFS_COMPLETIONS],
    ['string.', STRING_EXT],
    ['table.',  TABLE_EXT],
    ['math.',   MATH_EXT],
];

// ── Completion source ─────────────────────────────────────────────────────────

export function luaCompletionSource(context: CompletionContext): CompletionResult | null {
    for (const [prefix, completions] of NAMESPACE_MAP) {
        const escaped = prefix.replace(/\./g, '\\.');
        const m = context.matchBefore(new RegExp(escaped + '\\w*'));
        if (m) {
            return {
                from: m.from + prefix.length,
                options: completions,
                validFor: /^\w*/,
            };
        }
    }

    const word = context.matchBefore(/\w+/);
    if (!word && !context.explicit) return null;
    return {
        from: word ? word.from : context.pos,
        options: GLOBAL_COMPLETIONS,
        validFor: /^\w*/,
    };
}
